### PR TITLE
BME logo looks poorly in the printing template of the PowerPoint presentation

### PR DESCRIPTION
**Pull request by molnargab**
The BME logo on the footer of the slides looks somewhat poorly (screenshot from presentation mode):
before

I have applied the higher resolution logo from [the official site](http://www.bme.hu/sites/default/files/mediakit/bme_logo_nagy.jpg).
With the changes made, the logo now looks like:
after.

I have also compressed the image to 220 dpi, to maintain the file size.

### CODE REVIEW

**Comment by darvasd** [comment]
IMHO we should use the version with less details, see for example in the thesis template (https://github.com/FTSRG/thesis-template-latex/blob/master/src/figures/bme_logo.pdf). These logos are too detailed, thus they will necessarily look ugly in small size.
Also, it'd be better to use PNG format.

**Comment by szarnyasg** [comment]
@molnargab thanks for the pull request. I agree with @darvasd that we should use the less detailed version of the logo.

> Also, it'd be better to use PNG format.
> I'd personally use EMF for including the figure. Did you encounter any compatibility issues with EMF?

**Comment by darvasd** [comment]
No, I don't remember any problem. If the PDF export is fine, I agree, EMF is better than PNG, but PNG is still better than JPG.

**Comment by molnargab** [comment]
Thanks for the suggestions.

I've replaced the logo with a 220 DPI PNG export (top in the image below) of [the SVG image](https://github.com/FTSRG/templates/blob/master/logos/bme-logo-lowres.svg).

EMF looked somewhat funny on my screen resolution (middle):
compare

**Comment by steindani** [comment]
I'm really interested in seeing what happens when the low-res SVG is imported into a Visio file and inserted as an object.

**Comment by molnargab** [comment]
@steindani, just did a quick check, it's similar to the EMF version (though on higher resolutions it may look better than the PNG).

By the way, wouldn't having an embedded Visio object require the machine to have Visio installed?

**Comment by steindani** [comment]
@molnargab no, if the user does not have Visio installed, an alternate
image is shown. I'm not sure whether it is a raster image or not.

**Pull request merged**
